t ?= esp32

SERIAL_LOGFILE := serialout.txt
TERMINAL_SPEED := 115200
TERMINAL_EXTRA_FLAGS := -C $(SERIAL_LOGFILE)
LIBRARIES = SimpleTimer PS2KeyRaw
BUILD_USER := $(SERIAL_LOGFILE)

#CPPFLAGS = -DDEBUGGING=0xff -DTERMINAL_SPEED=$(TERMINAL_SPEED)

ifeq ($t, tivac)
BOARD := EK-LM4F120XL

CPPFLAGS = -DHARDWARE_H=\"hw/stellarpad-example.h\"
LIBRARIES += UTFT SD SpiRAM
endif

ifeq ($t, esp8266)
BOARD := d1_mini
BAUD := 921600
FS_DIR := data
EESZ := 4M1M
F_CPU := 80

# bit-banged sound on CB2 (experimental: PWM sound is cleaner)
#CPPFLAGS = -DSIMPLE_TIMER_MICROS -DCPU_INSTRUCTIONS=10 -DBIT_BANG_SOUND
CPPFLAGS += -DUSER_SETUP_LOADED -DILI9341_DRIVER -DTFT_CS=PIN_D8 -DTFT_DC=PIN_D1 \
	-DTFT_RST=-1 -DSPI_FREQUENCY=40000000 -DLOAD_GLCD \
	-DHARDWARE_H=\"hw/esp8bit.h\"
LIBRARIES += TFT_eSPI SpiRAM LittleFS
endif

ifeq ($t, esp32)
UPLOADSPEED := 921600
FS_DIR := data
LIBRARIES += FS SPIFFS

ifeq ($b, lilygo)
BOARD := ttgo-t7-v14-mini32
SERIAL_PORT := /dev/ttyACM0
CPPFLAGS += -DHARDWARE_H=\"hw/ttgo-t7-v14-mini32.h\" -DVGA_RESOLUTION=VGAMode::MODE400x300 -DROM_SET=series4
LIBRARIES += ESP32Lib

else
BOARD := lolin32
CPPFLAGS += -DUSER_SETUP_LOADED -DILI9341_DRIVER -DTFT_CS=5 -DTFT_DC=2 \
	-DTFT_RST=-1 -DSPI_FREQUENCY=40000000 -DLOAD_GLCD \
	-DHARDWARE_H=\"hw/esp32-example.h\"
LIBRARIES += TFT_eSPI
endif
endif

include $t.mk
